extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  bearertokenauth/otlp-export:
    filename: "otlp-export.token"
  file_storage/state:
    directory: /home/otelcol/storage
    create_directory: true
    recreate: true # when set, the filestorage extension will automatically rename the corrupted bbolt database and create a new one when certain bbolt panics occur
    compaction:
      directory: /tmp/otelcol
      on_start: true
      on_rebound: true
      rebound_needed_threshold_mib: 1024
      rebound_trigger_threshold_mib: 100
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  journald:
#    directory: /var/log/journal # defaults to /run/log/journal or /run/journal
    storage: file_storage/state
    operators:
      - id: add_journald_id
        type: add
        field: resource.otel_logs_receiver
        value: journald
      - id: move_all_to_attrs
        type: move
        from: body
        to: attributes.journald
      - id: move_journald_message
        type: move
        from: attributes.journald.MESSAGE
        to: body
      - id: flatten_journald_attributes
        type: flatten
        field: attributes.journald
  prometheus/node:
    config:
      scrape_configs:
        - job_name: node
          static_configs:
            - targets: ['localhost:9100']
  prometheus/postgres:
    config:
      scrape_configs:
        - job_name: postgres
          static_configs:
            - targets: ['localhost:9187']
  filelog/postgresql_json:
    include:
      # Even in case of upgrades, we automatically follow the new log files
      - /dat/16/data/pg_log/postgresql*.json
      - /dat/17/data/pg_log/postgresql*.json
      - /dat/18/data/pg_log/postgresql*.json
      - /dat/19/data/pg_log/postgresql*.json
      - /dat/20/data/pg_log/postgresql*.json
      - /dat/21/data/pg_log/postgresql*.json
      - /dat/22/data/pg_log/postgresql*.json
      - /dat/23/data/pg_log/postgresql*.json
      - /dat/24/data/pg_log/postgresql*.json
    operators:
      - type: json_parser
        severity:
          parse_from: attributes.error_severity # The field name in your JSON log for the log level
          mapping:
            debug:
              - DEBUG1
              - DEBUG2
              - DEBUG3
              - DEBUG4
              - DEBUG5
            info:
              - INFO
              - LOG
              - NOTICE
              - DETAIL
            warn: WARNING
            error: ERROR
            fatal:
              - FATAL
              - PANIC
        on_error: send
      - type: add
        field: resource.otel_logs_receiver
        value: postgresql
exporters:
  nop:
  debug:
    verbosity: detailed
  file:
    path: /tmp/otel-logs/postgresql.json # for testing
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 3
  otlp/export:
    endpoint: ~ # overridden by otel-config-override
    compression: zstd
    timeout: 30s
    # TODO: add auth
processors:
  resourcedetection/ec2:
    detectors: [ "ec2" ]
  resource/datagres:
    attributes:
      - key: service.source
        value: datagres
        action: upsert
  resource/ubiMetadata:
    attributes: [ ]
service:
  extensions:
    - health_check
    - file_storage/state
  pipelines:
    logs:
      receivers:
        - otlp
        - filelog/postgresql_json
        - journald
      processors:
        - resource/datagres
        - resourcedetection/ec2
        - resource/ubiMetadata
      exporters:
#        - debug
#        - file
        - nop
        - otlp/export
    metrics:
      receivers:
        - otlp
        - prometheus/node
        - prometheus/postgres
      processors:
        - resource/datagres
        - resourcedetection/ec2
        - resource/ubiMetadata
      exporters:
        - nop
        - otlp/export
    traces:
      receivers:
        - otlp
      processors:
        - resource/datagres
        - resourcedetection/ec2
        - resource/ubiMetadata
      exporters:
        - nop
        - otlp/export
  telemetry:
    resource:
      service.otelcol.location: 'postgres_resource'
    logs:
      encoding: console
